name: Deployment workflow
on: [push, workflow_dispatch] # making this job to run automatically, also manually
jobs:
  Testjob:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v6
      - name: Install the packages
        run: npm ci
      - name: Test the code
        run: npm run test 
  DeployJob:
    needs: Testjob  #Making this job to run after the Testjob completes successfully
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v6
      - name: Install the packages
        run: npm ci
      - name: Build the code
        run: npm run build
      - name: Deploy the code
        run: echo "Deploying ..."   