name: Test workflow
on: push
jobs:
  Testjob:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v6
      - name: Install the packages
        run: npm ci
      - name: Test the code
        run: npm run test 
  DeployJob:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v6
      - name: Install the packages
        run: npm ci
      - name: Build the code
        run: npm run Build
      - name: Deploy the code
        run: echo "Deploying ..."   